### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by shingionline** [mlandauer/cuttlefish#145]
Hello everyone,

Is there a place where I can get step-by-step instructions on how to install Cuttlefish for the absolute beginner? I have a server with Ubuntu 14.04 but I have never worked with ruby applications before.

The instructions available seem to be written for a Ruby expert eg:-

Edit config/deploy.rb

What needs to be edited in this file? 

cap deploy:setup
cap deploy:cold (the first time)

???

This looks like a great piece of software but I am very confused about how to get it running :-(

Please help.

**Comment by kiawin** [comment]
I'm following the README to install cuttlefish.io

However I bumped into  many (undocumented) undefined ansible variables when i ran provision_production.sh

I will compile a list of variables to be included in playbook.yml and if you think this is good for README, I can make a pull request :)
