### ISSUE TITLE
No install instructions work for current Debian

### ISSUE THREAD

**Issue by handelaar** [mlandauer/cuttlefish#195]
After about two hours mucking around with rbenv, installing alternate versions of Ruby in a profile, setting global environment flags (for some reason), and finally getting "bundle install" to not die half way through, we get:

$ bundle exec rake db:setup
git://github.com/capistrano/maintenance.git (at master) is not yet checked out. Run `bundle install` first.

...from a system that just installed Capistrano like fourteen seconds ago.

Error messages are clearly incorrect. I give up.

**Comment by jpmckinney** [comment]
`bundle install` and `bundle exec rake db:setup` ran without issue for me. I didn't have to do any mucking since I already had rbenv and Ruby 2.1.5. The error message, which says "Run bundle install first." suggests that bundle install did not terminate without error.

**Comment by handelaar** [comment]
bundle install runs without error.

**Comment by jpmckinney** [comment]
It's hard to diagnose without more information. It's possible that the mucking produced a broken environment.

**Comment by handelaar** [comment]
In fact it's fairly obvious that 'bundle install' and this task are running
different versions of ruby. The question would be why.

If any further information was actually provided by error messages, for
example, they'd have been attached.

**Comment by jpmckinney** [comment]
I don't think the issue is `bundle` using one Ruby for `install` and another Ruby for `exec`.

I think the problem is something in the way you installed rbenv. It shouldn't take two hours to install rbenv, and I imagine that in that time there was an opportunity to make some change that produced your current issue. I'd recommend starting over and documenting each command, so that it's possible to reproduce. Right now, it's impossible for anyone else to reproduce your error message.

**Comment by handelaar** [comment]
If the app install instructions, followed exactly from scratch, result in
no outcome, then the instructions are incomplete.

This is not a support query. It is a bug report against documentation.

"Works for me" based on your previously-installed setup happening to work
out of nothing more than good fortune is not a response to this bug report.
Please desist.

**Comment by jpmckinney** [comment]
Can you link to the documentation you're using? I can't find any docs mentioning Bundler. The only relevant docs I see are at https://github.com/mlandauer/cuttlefish#dependencies

**Comment by handelaar** [comment]
God *damnit*. This entire thing is on the wrong Issue list because I had two open at the same time. 

</idiot>
