### ISSUE TITLE
ERROR: Decryption failed on vagrant up

### ISSUE THREAD

**Issue by jpmckinney** [mlandauer/cuttlefish#196]
It gets to this step:

`PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/Users/james/Sites/shared/pulls/cuttlefish/.vagrant/machines/default/virtualbox/private_key --user=vagrant --connection=ssh --limit='default' --inventory-file=/Users/james/Sites/shared/pulls/cuttlefish/.vagrant/provisioners/ansible/inventory --vault-password-file=~/.cuttlefish_ansible_vault_pass.txt provisioning/playbook.yml`

which fails with `ERROR: Decryption failed`

Any idea? I don't know what's being decrypted. I don't know what the command does either.

**Comment by lorello** [comment]
I've the same problem, what vault password should we use?
```bash
ERROR: Decryption failed
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by lorello** [comment]
I've found a workaround to make the ansible playbook run:
    
    rm provisioning/roles/cuttlefish-app/vars/main.yml
    echo -e "---\ndb_password: foo\nprivate_ssl_key: foo" > provisioning/roles/cuttlefish-app/vars/main.yml

**Comment by harobed** [comment]
@lorello  success

**Comment by henare** [comment]
Closing this to consolidate these issues under #226.
