### ISSUE TITLE
Add instructions for sending email from php

### ISSUE THREAD

**Issue by mlandauer** [mlandauer/cuttlefish#200]
For example on page: https://cuttlefish.oaf.org.au/documentation#app-14

**Comment by mlandauer** [comment]
I'm assigning this to you @henare as you've just done this. Might be good to add these instructions to cuttlefish while it's still fresh in your mind

**Comment by mlandauer** [comment]
Unassign yourself if you don't feel like doing this @henare!

**Comment by henare** [comment]
Thanks @mlandauer. Luckily I'm in a documenting mood :pencil2: :green_book:
