### ISSUE TITLE
Setup failing.

### ISSUE THREAD

**Issue by gr8tushar** [mlandauer/cuttlefish#213]
Hi,
I am trying to setup cuttlefish on a fresh server as per the read me guide (To install on Linode). 
I am facing the following issue:
1. Because running step 9, I had to empty the provisioning/roles/cuttlefish-app/vars/main.yml file. Else it was giving me Decryption error.
2. After running step 9, it gives me the following error:

root@localhost:~/cuttlefish# ./provision_production.sh

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
fatal: [lixxxx.members.linode.com] => SSH Error: Permission denied (publickey,password).
    while connecting to 139.162.xxx.xxx:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

TASK: [deploy-user | Ensure we have a deploy group] ***************************
FATAL: no hosts matched or all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/playbook.retry

xxxx.members.linode.com : ok=0    changed=0    unreachable=1    failed=0

**Comment by gr8tushar** [comment]
I started with the whole setup again. 
What is the value that I need to enter cuttlefish_ansible_vault_pass.txt . How do I know what value was used for encrypting the values in provisioning/roles/cuttlefish-app/vars/main.yml

**Comment by henare** [comment]
Closing this to consolidate these issues under #226.
