### ISSUE TITLE
Suggest append prerequisite section to README

### ISSUE THREAD

**Issue by harobed** [mlandauer/cuttlefish#219]
Suggest : 

* here https://github.com/mlandauer/cuttlefish#to-install
* append : 

```
Prerequisite : 

* Vagrant(https://www.vagrantup.com/downloads.html) (>=1.7.4)
* ansible(http://docs.ansible.com/ansible/intro_installation.html) (>= 1.9.4)
```

**Comment by henare** [comment]
This is probably a good idea but I think it should be picked up under #226 so I'll close this one.
