### ISSUE TITLE
Remove references to MySQL in the README

### ISSUE THREAD

**Issue by athoune** [mlandauer/cuttlefish#223]
In the README and Ansible, half of time, it's Mysql, the other half is Postgresql.

**Comment by henare** [comment]
:+1: well spotted. AFAIK the project was changed from MySQL to PostgreSQL.

Obviously that means we should remove references to MySQL.

**Comment by Serkan-devel** [comment]
#246 pls halp

**Comment by mlandauer** [comment]
This is done
