### ISSUE TITLE
Automatically archive emails over 6 months old

### ISSUE THREAD

**Issue by henare** [mlandauer/cuttlefish#232]
I think it's very rare to want to look at deliveries over 6 months old in the UI. To keep disk space manageable (at least on the OAF server) we should just automatically archive them to S3 (so we need to do #231 beforehand).

**Comment by henare** [comment]
This should also include removing the archive files from disk after they're transferred to S3, which is something we do manually at the moment.

**Comment by equivalentideas** [comment]
From @henare in chat:

> my approach would be to run a cron job every day  ...
> you should be able to run it anytime and it will archive all deliveries older than 6 months
