### ISSUE TITLE
Transparently send mail from your own domain - TXT record in DNS

### ISSUE THREAD

**Issue by schlos** [mlandauer/cuttlefish#233]
In app page "Transparently send mail from your own domain" (https://cuttlefish.oaf.org.au/apps/NUMBER_OF_APP/dkim) I'm keep getting info toast notification "You will need to add two TXT records to your DNS."

It's a bit puzzling because in settings displayed below for copy paste, I see only one record:
- one domain "cuttlefish._domainkey.MY_CUSTOM_DOMAIN"
- with blob of TXT key (only 1 big chunk of text).

Now, later on, and while reading issue #229 I've realized that there might be two records inside that blob:
k=
p=

Both k and p TXT records are in same TXT blob, and I'm unsure - can I add it in DNS as only one record? if yes, is only semicolon and space separation enough if it's in one TXT record?

Cause I've tried both 
- 2 seperate DNS TXT keys 
- and to add all TXT in one value on DNS, 

but I'm keep seeing notification "You will need to add two TXT records to your DNS" and "Reload this page after you have configured your DNS".

Tried reloading and wondering also - does cuttlefish check DNS records on the fly or it's scheduled job that runs every X time? I mean, TTL on DNS is set to 4 minutes, and it should already picked TXT record(s). Is in that case message "Reload this page after you have configured your DNS" misleading (keeping me to refresh page)?

**Comment by extremeshok** [comment]
You will need a txt spf record and a domain key txt record

**Comment by schlos** [comment]
thanks for that.

will Cuttlefish show me which spf record I need to create in 2nd step? When will be displayed that 2nd step (spf record guide)?

How much time Cuttlefish need to verify that TXT record exist (step 1)?
