### ISSUE TITLE
More than 10% of messages are being held back

### ISSUE THREAD

**Issue by henare** [mlandauer/cuttlefish#235]
This week 7,071 messages were held back out of a total of 72,033. Is that a lot or to be expected?

**Comment by cenourinha** [comment]
You should check the logs to know why the messages aren't being delivered.

**Comment by henare** [comment]
Thanks for the tip @cenourinha. In Cuttlefish it actually shows you the reason right next to the email. My question is whether holding back 10% of messages is a lot for the kind of sites @openaustralia runs.

**Comment by henare** [comment]
I'm pretty sure the cause of this is #121 and since it's a downstream issue I'm closing this in favour of https://github.com/openaustralia/cuttlefish/issues/3.
