### ISSUE TITLE
Test email not sent

### ISSUE THREAD

**Issue by flyerfred** [mlandauer/cuttlefish#274]
Hi all,

I have what seems to be a clean Cuttlefish installation, with Redis, Postfix running. Postfix has been tested OK independantly (using mailx). But, after creating an app in Cuttlefish, I can not send the test mail using "Test/Test email" in the Dashboard.

The SMTP process is launched like this, but does not say anything when the Test email is triggered:

tupromail@be-s2534-msl:~/cuttlefish-master$ **bundle exec rake cuttlefish:smtp RAILS_ENV=production**
My eight arms and two tentacles are quivering in anticipation.
I'm listening for emails via SMTP on 0.0.0.0 port 2525
I'm in the production environment

There is nothing arriving in Postfix when the Cuttlefish Dashboard displays "email sent".

How to debug this? The production log does not show anything,

Thanks a lot!

**Comment by henare** [comment]
I think the emails are sent using the background queue (sidekiq in this case).

Rather than starting individual services you can use Foreman to start all of the required processes at the same time:

```bundle exec foreman start```

**Comment by flyerfred** [comment]
Thanks Henare.

The Procfile contains the following:


smtp: bundle exec rake cuttlefish:smtp
log: bundle exec rake cuttlefish:log
sidekiq: bundle exec sidekiq
web: bundle exec rails s

Are you talking about sidekiq:bundle exec sidekiq ?
