### ISSUE TITLE
Error when inviting someone to be administrator

### ISSUE THREAD

**Issue by flyerfred** [mlandauer/cuttlefish#279]
I have a Cuttlefish server running, and I am administrator on it, as first one to have loggued in this new server.

When I try to invite someone else, the invitation email is not received by the invited one, and I get the following error:

```
SocketError in InvitationsController#create 
getaddrinfo: Name or service not known

# Make the invited user part of the same team as the person doing the inviting
  def invite_resource
    resource_class.invite!(invite_params.merge(team_id: current_inviter.team_id), current_inviter)
  end

  def after_invite_path_for(resource)

app/controllers/invitations_controller.rb:20:in `invite_resource'
app/controllers/invitations_controller.rb:8:in `create'
```

If I'm not wrong, this problem appeared after I changed the base URL used to insert links in sent mails, in the environment files, with:

`
config.action_mailer.default_url_options = { host: "#{config.cuttlefish_domain}" }`

and setting in the environment:

`export CUTTLEFISH_DOMAIN=mydomain`

Any idea?

Thanks, F.

**Comment by henare** [comment]
I'm pretty sure that exception is because Rails can't connect to the mail server to send the invite.

`getaddrinfo: Name or service not known`

You need to make sure that `CUTTLEFISH_DOMAIN` is resolvable by the server and that it resolves to localhost.

**Comment by flyerfred** [comment]
That was it, thanks! Domain resolution was wrong (it was with a bad IP address). After fixing that, it's OK!

Thanks a lot, F.
