### ISSUE TITLE
Counting URL malformed

### ISSUE THREAD

**Issue by flyerfred** [mlandauer/cuttlefish#281]
Hi all,

I noticed that the URL contained in sent mails from Cuttlefish.io are malformed, and here is an example:

`<a href="http://localhost:3000/l2/7/c2617d461e022a8d0679a4b4352941f301f7ffcb?url=http%3A%2F%2Fmail.ip.is.echonet%2Fadmins%2Finvitation%2Faccept%3Finvitation_token%3D74a6C_5UbzAcegf_rsWx">Accept invitation</a>`

- the first "http://localhost:3000" in the href value is wrong: it should be our domain

- the second part of the URL is correct (mail.ip.is.echonet)

How to do to have the first part of the URL use the right domain? Seems CUTTLEFISH_DOMAIN variable is used for the second part, but not the first...

Thank you!

Fred

**Comment by mlandauer** [comment]
The `CUTTLEFISH_DOMAIN` environment variable should set that domain. Are you sure that the environment variable is getting set? The domain in the second part of the url is just coming from the email that you sent...
