### ISSUE TITLE
Redirect to localhost in production mode

### ISSUE THREAD

**Issue by flyerfred** [mlandauer/cuttlefish#282]
Hi all,

We noticed a difference between development & production environments: in production environment, the web server redirects to localhost when going to the home page. Cuttlefish web server is running behind a nginx proxy.

Here is the production.log part showing the problem:

```
Started GET "/admins/sign_in" for 127.0.0.1 at 2017-03-07 17:51:40 +0100
Processing by Admins::SessionsController#new as HTML
Redirected to https://localhost/admins/sign_in
Filter chain halted as #<Proc:0x00000004ae4210@/soft/wordpress/home/tupromail/.gem/ruby/gems/actionpack-4.2.7.1/lib/action_controller/metal/force_ssl.rb:65> rendered or redirected
Completed 301 Moved Permanently in 1ms (ActiveRecord: 0.0ms)
```

Question is: how to parameter Cuttlefish to have it not redirect to localhost?

Thank you

**Comment by mlandauer** [comment]
You need to set the environment variable `CUTTLEFISH_DOMAIN` in production
