### ISSUE TITLE
cuttlefish.io is not valid HTTPS

### ISSUE THREAD

**Issue by erlend-sh** [mlandauer/cuttlefish#285]
https://cuttlefish.io/ returns:

<img width="664" alt="screen shot 2017-04-24 at 18 16 24" src="https://cloud.githubusercontent.com/assets/583842/25359089/2addc556-291a-11e7-9450-bb115efa4ce6.png">

**Comment by terribleplan** [comment]
The site currently uses a certificate issued by "StartCom Class 1 DV Server CA" which has been distrusted by chrome due to numerous security incidents with StartCom and WoSign.

I would suggest Let's Encrypt as a free alternative.

**Comment by thibaultmol** [comment]
@mlandauer Please fix this as soon as possible. I'm new to this tool (found it on google). But if you're greeted with an HTTPS bad certificate error , that's an instant turn off for a lot of people (I found your github page though)

**Comment by Serkan-devel** [comment]
You can switch to let's encrypt

**Comment by kitsched** [comment]
Another vote for Let's encrypt.

**Comment by silverark** [comment]
Another Vote for Let's Encrypt. I can help install it if you need some help. Love the project btw.

**Comment by almereyda** [comment]
What can we do to help here?

**Comment by AlJohri** [comment]
Bumping this:

<img width="969" alt="screen shot 2017-10-28 at 6 42 11 pm" src="https://user-images.githubusercontent.com/2790092/32139165-ce6ef3a6-bc0f-11e7-83ca-667de9806e46.png">

**Comment by Serkan-devel** [comment]
Is this project ded?

**Comment by mlandauer** [comment]
Thanks for your patience! This is now fixed.
