### ISSUE TITLE
Rejig app concept around domain

### ISSUE THREAD

**Issue by mlandauer** [mlandauer/cuttlefish#298]
Really a single app relates to emails from a single domain so it would make more sense to make this really clear. Right now it's kind of implied.

**Comment by jamezpolley** [comment]
I agree that the current app concept is largely a proxy for domain; but I would prefer to break this linkage (making apps and domains more separate) rather than seeing it become more tied.

I've raised #299 to give more information about my use case

**Comment by mlandauer** [comment]
After seeing the use case in #299 it's clear that this idea is a bit misguided. Closing this in favour of #299.
