### ISSUE TITLE
[Enhancement] NextCloud integration 

### ISSUE THREAD

**Issue by jcklpe** [mlandauer/cuttlefish#321]
[Nextcloud ](https://nextcloud.com/)is a super rad open source cloud platform application that rivals Google Drive in it's capabilities. It even has mail integration but it lacks more sophisticated tools like email tracking, auto response, email templates, scheduling integration, etc. 

I would love to see Cuttlefish contribute some of their ideas and works to NextCloud. The two would gain a ton by leveraging each other's tools!

I would also be willing to contribute my skillsets if needed. I work as a designer/web dev and though I couldn't do this all on my own I would certainly be willing to help.

**Comment by mlandauer** [comment]
I don't really see how these things connect. Cuttlefish isn't a tool for use by "end users". So, closing this.
