### ISSUE TITLE
GraphQL::Client::UnimplementedFieldError in Apps#dkim

### ISSUE THREAD

**Issue by skob** [mlandauer/cuttlefish#326]
After configuring dkim I get this exception
```
Showing cuttlefish/app/views/apps/dkim.html.haml where line #12 raised:

undefined field `legacy_dkim_selector' on App type. https://git.io/v1y3m
```

**Comment by mlandauer** [comment]
Thanks @skob for finding this error and reporting it! It should be fixed now in master. Please let us know if it doesn't work for you or if you find any other problems.
