### ISSUE TITLE
Error running docker-compose

### ISSUE THREAD

**Issue by fernandobrunelli** [mlandauer/cuttlefish#339]
I'm trying to run a development environmnet following the instructions for docker-compose but it throws an error:
ActiveRecord::RecordInvalid: Validation failed: From domain doesn't have a DNS record configured correctly for cuttlefish._domainkey.foo.com

Any tip?

Full log:
# docker-compose run web bundle exec rake db:setup
Starting cuttlefish_smtp_1 ...
Starting cuttlefish_redis_1 ... done
Starting cuttlefish_db_1 ... done
Database 'cuttlefish_development' already exists
Database 'cuttlefish_test' already exists
-- enable_extension("plpgsql")
   -> 0.0206s
-- create_table("addresses", {:force=>:cascade})
   -> 1.6014s
-- create_table("admins", {:force=>:cascade})
   -> 2.1686s
-- create_table("apps", {:force=>:cascade})
   -> 0.8364s
-- create_table("click_events", {:force=>:cascade})
   -> 0.4169s
-- create_table("deliveries", {:force=>:cascade})
   -> 2.1935s
-- create_table("delivery_links", {:force=>:cascade})
   -> 1.3480s
-- create_table("deny_lists", {:force=>:cascade})
   -> 0.3339s
-- create_table("emails", {:force=>:cascade})
   -> 0.5594s
-- create_table("links", {:force=>:cascade})
   -> 0.1819s
-- create_table("open_events", {:force=>:cascade})
   -> 2.8723s
-- create_table("postfix_log_lines", {:force=>:cascade})
   -> 0.8529s
-- create_table("teams", {:force=>:cascade})
   -> 0.4345s
-- add_foreign_key("emails", "addresses", {:column=>"from_address_id", :name=>"emails_from_address_id_fk"})
   -> 0.1079s
-- add_foreign_key("emails", "apps", {:name=>"emails_app_id_fk", :on_delete=>:cascade})
   -> 0.0153s
-- add_foreign_key("postfix_log_lines", "deliveries", {:name=>"postfix_log_lines_delivery_id_fk", :on_delete=>:cascade})
   -> 0.0076s
-- enable_extension("plpgsql")
   -> 0.0217s
-- create_table("addresses", {:force=>:cascade})
   -> 1.0393s
-- create_table("admins", {:force=>:cascade})
   -> 2.1751s
-- create_table("apps", {:force=>:cascade})
   -> 0.3992s
-- create_table("click_events", {:force=>:cascade})
   -> 0.3837s
-- create_table("deliveries", {:force=>:cascade})
   -> 1.0759s
-- create_table("delivery_links", {:force=>:cascade})
   -> 0.3745s
-- create_table("deny_lists", {:force=>:cascade})
   -> 0.3228s
-- create_table("emails", {:force=>:cascade})
   -> 5.6846s
-- create_table("links", {:force=>:cascade})
   -> 0.5681s
-- create_table("open_events", {:force=>:cascade})
   -> 0.4655s
-- create_table("postfix_log_lines", {:force=>:cascade})
   -> 2.9636s
-- create_table("teams", {:force=>:cascade})
   -> 0.7286s
-- add_foreign_key("emails", "addresses", {:column=>"from_address_id", :name=>"emails_from_address_id_fk"})
   -> 0.0880s
-- add_foreign_key("emails", "apps", {:name=>"emails_app_id_fk", :on_delete=>:cascade})
   -> 0.2066s
-- add_foreign_key("postfix_log_lines", "deliveries", {:name=>"postfix_log_lines_delivery_id_fk", :on_delete=>:cascade})
   -> 0.3109s
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: From domain doesn't have a DNS record configured correctly for cuttlefish._domainkey.foo.com
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/validations.rb:80:in `raise_validation_error'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/validations.rb:52:in `save!'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/transactions.rb:315:in `block in save!'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/transactions.rb:386:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:252:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/transactions.rb:383:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/transactions.rb:315:in `save!'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/suppressor.rb:48:in `save!'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:374:in `insert_record'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/has_many_association.rb:36:in `insert_record'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:362:in `block (2 levels) in _create_record'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:455:in `replace_on_target'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:284:in `add_to_target'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:360:in `block in _create_record'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:136:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:230:in `block in within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:227:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:135:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:359:in `_create_record'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/has_many_association.rb:123:in `_create_record'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/association.rb:186:in `create!'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/collection_proxy.rb:366:in `create!'
/app/db/seeds.rb:47:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
/usr/local/bundle/gems/railties-5.2.0/lib/rails/engine.rb:551:in `load_seed'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)

**Comment by jseparovic** [comment]
@fernandobrunelli any luck with this one? I'm getting the same issue and it's not clear where to configure the domain

**Comment by fazlerabbi37** [comment]
@fernandobrunelli  see this comment https://github.com/mlandauer/cuttlefish/issues/340#issuecomment-495151883. this should fix it.

**Comment by mlandauer** [comment]
As mentioned in #340 this has been fixed by 8daaf1bc341cb65e11e734ee348454f3c68f4ecc
