### ISSUE TITLE
This site can’t be reached: cuttlefish.oaf.org.au - ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by schlos** [mlandauer/cuttlefish#343]
Today I'm getting this:

This site can’t be reached
cuttlefish.oaf.org.au refused to connect.

ERR_CONNECTION_REFUSED

**Comment by mlandauer** [comment]
Thanks for letting us know. That's all fixed now. The web ui had gotten stuck but the SMTP server was all still working.
