### ISSUE TITLE
Integrated lookup of ip address

### ISSUE THREAD

**Issue by mlandauer** [mlandauer/cuttlefish#374]
We record ip addresses for clicks and opens. It would be useful to integrate a lookup of information about that IP address.

https://ip-api.com/ looks like a very useful free service for non-commercial use. It's limited to 45 request per minute which should work fine for us.

**Comment by katska** [comment]
Can you let me know when you're going to start on this? Thanks!

**Comment by mlandauer** [comment]
@katska I'm in the mood to do this this morning. Can't exactly explain why! :-)
