### ISSUE TITLE
Webhook URL cannot be configured - "something went wrong" error

### ISSUE THREAD

**Issue by schlos** [mlandauer/cuttlefish#392]
When I specify Webhook URL on configuration page:
`https://cuttlefish.oaf.org.au/apps/33/webhook`

on form submit I get following error:
> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

It's reproducible also on all other apps (i.e. ID 24).

**Comment by mlandauer** [comment]
@schlos this should be fixed now and rolled out to production. See #393. 

Thanks for reporting the problem!
