### ISSUE TITLE
Smart route

### ISSUE THREAD

**Issue by ravivgolov** [mlandauer/cuttlefish#439]
Hello

Can an external SMTP be connected to the app to route all outgoing emails using another SMTP instead of internal postfix?

**Comment by mlandauer** [comment]
Yup should be possible though it has caveats. Set the environment variable `POSTFIX_SMTP_HOST` for the cuttlefish app and it will send via an external postfix server. See https://github.com/mlandauer/cuttlefish/blob/b78fa850174f17b236f61f8edfb2d7e1a3bc9140/config/application.rb#L53

However, you will need to be able to mount the log files of that external SMTP host to a local filesystem if you want any of the deliverability stuff to work.
